spring:
  datasource:
    driverClassName: com.cloudera.impala.jdbc.Driver
    url: jdbc:impala://quickstart-bigdata:21050/@impala.db.name@
  kafka:
    producer:
      bootstrap-servers: quickstart-bigdata:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 1
      properties:
        delivery.timeout.ms: 10000
        max.block.ms: 15000
        request.timeout.ms: 5000
        reconnect.backoff.ms: 10000
        retry.backoff.ms: 10000
        linger.ms: 5000
topic:
  webdisp: 1357-disp-webdisp-@spring.profiles.active@
  jarvis: 1357-disp-jarvis-@spring.profiles.active@
  int002: 1357-disp-int002-@spring.profiles.active@
